import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { Role } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { InventoryService } from '../inventory/inventory.service';
import { documentNo } from '../common/numbering';
import { AuthUser } from '../common/auth-user';
import { ApproveKnittingDto, ApproveYarnDto, CreateDyeingBatchDto, CreateFinishingDto, CreateKnittingJobDto, DyeingEntryDto, FinalQcDto, KnittingEntryDto, YarnEntryDto } from './dto/production.dto';

@Injectable()
export class ProductionService {
 constructor(private prisma:PrismaService,private inventory:InventoryService){}
 private canWork(user:AuthUser,assigned?:string|null){ if(user.role==='WORKER' && assigned && assigned!==user.id) throw new ForbiddenException('This job is assigned to another worker'); }
 private async requireProductionOrder(id:string){const order=await this.prisma.productionOrder.findUnique({where:{id},select:{id:true}});if(!order)throw new NotFoundException('Production order not found. Refresh the page and select an existing production order.');}
 async context(){ const [productionOrders,warehouses,machines,workers,greyRolls]=await Promise.all([this.prisma.productionOrder.findMany({where:{status:{notIn:['CLOSED','REJECTED']}},include:{salesOrder:{include:{customer:true}},salesOrderItem:true},orderBy:{createdAt:'desc'}}),this.prisma.warehouse.findMany({where:{active:true},orderBy:{code:'asc'}}),this.prisma.machine.findMany({where:{status:{not:'DISABLED'}},orderBy:{code:'asc'}}),this.prisma.user.findMany({where:{role:'WORKER',status:'ACTIVE'},select:{id:true,name:true,email:true,employeeId:true}}),this.prisma.greyFabricRoll.findMany({where:{qcStatus:'PASSED'},include:{dyeingLinks:true,knittingJob:true},orderBy:{createdAt:'desc'}})]); return {productionOrders,warehouses,machines,workers,greyRolls:greyRolls.filter(r=>r.dyeingLinks.length===0)}; }
 async myJobs(user:AuthUser){ if(user.role!=='WORKER') return {knitting:[],dyeing:[]}; const [knitting,dyeing]=await Promise.all([this.prisma.knittingJob.findMany({where:{assignedWorkerId:user.id,status:{notIn:['COMPLETED','CLOSED','REJECTED']}},include:{productionOrder:{include:{salesOrder:{include:{customer:true}},salesOrderItem:true}},machine:true},orderBy:{updatedAt:'desc'}}),this.prisma.dyeingBatch.findMany({where:{assignedWorkerId:user.id,status:{notIn:['COMPLETED','CLOSED','REJECTED']}},include:{productionOrder:{include:{salesOrder:{include:{customer:true}},salesOrderItem:true}},machine:true},orderBy:{updatedAt:'desc'}})]); return {knitting,dyeing}; }
 async yarnEntry(dto:YarnEntryDto,user:AuthUser){const balance=dto.inputKg-dto.outputKg-dto.wasteKg;if(balance<-0.001)throw new BadRequestException('Output + waste cannot exceed input');await this.requireProductionOrder(dto.productionOrderId);return this.prisma.yarnProductionEntry.create({data:{entryNo:documentNo('YN'),...dto,balanceKg:balance,workerId:user.id}});}
 async approveYarn(id:string,dto:ApproveYarnDto,user:AuthUser){return this.prisma.$transaction(async tx=>{const e=await tx.yarnProductionEntry.findUnique({where:{id}});if(!e)throw new NotFoundException('Yarn entry not found');if(e.approved)throw new BadRequestException('Entry already approved');await tx.yarnProductionEntry.update({where:{id},data:{approved:true}});await this.inventory.createTxn({category:'YARN',txnType:'PRODUCTION_IN',itemCode:e.yarnCount,itemName:`Yarn ${e.yarnCount}`,lotNo:e.lotNo,warehouseId:dto.warehouseId,quantityIn:Number(e.outputKg),referenceType:'YARN_PRODUCTION',referenceId:e.id,productionOrderId:e.productionOrderId,createdById:user.id},tx);if(Number(e.wasteKg)>0)await tx.wasteEntry.create({data:{productionOrderId:e.productionOrderId,process:'Yarn Production',quantityKg:e.wasteKg,reason:'Process waste',machineCode:e.machineCode,workerName:e.workerId,approvedBy:user.id}});return {success:true,message:'Yarn entry approved and stock posted'};});}
 async createKnittingJob(dto:CreateKnittingJobDto,user:AuthUser){return this.prisma.$transaction(async tx=>{await this.inventory.requireStock('YARN',dto.yarnCount,dto.yarnWarehouseId,dto.yarnIssuedKg,dto.yarnLotNo,tx);const j=await tx.knittingJob.create({data:{jobNo:documentNo('KN'),productionOrderId:dto.productionOrderId,yarnLotNo:dto.yarnLotNo,yarnCount:dto.yarnCount,fabricType:dto.fabricType,gsm:dto.gsm,diameter:dto.diameter,gauge:dto.gauge,machineId:dto.machineId,assignedWorkerId:dto.assignedWorkerId,yarnIssuedKg:dto.yarnIssuedKg,status:'MATERIAL_ISSUED'}});await this.inventory.createTxn({category:'YARN',txnType:'KNITTING_ISSUE',itemCode:dto.yarnCount,itemName:`Yarn ${dto.yarnCount}`,lotNo:dto.yarnLotNo,warehouseId:dto.yarnWarehouseId,quantityOut:dto.yarnIssuedKg,referenceType:'KNITTING_JOB',referenceId:j.id,productionOrderId:dto.productionOrderId,createdById:user.id},tx);if(dto.assignedWorkerId)await tx.notification.create({data:{userId:dto.assignedWorkerId,title:'New knitting job assigned',message:`${j.jobNo} • ${dto.fabricType} • ${dto.yarnIssuedKg} KG`,type:'JOB_ASSIGNED',referenceType:'KNITTING_JOB',referenceId:j.id}});return j;});}
 async knittingEntry(jobId:string,dto:KnittingEntryDto,user:AuthUser){const j=await this.prisma.knittingJob.findUnique({where:{id:jobId},include:{entries:true}});if(!j)throw new NotFoundException('Knitting job not found');this.canWork(user,j.assignedWorkerId);const used=j.entries.reduce((a,e)=>a+Number(e.outputKg)+Number(e.wasteKg),0);const balance=Number(j.yarnIssuedKg)-used-dto.outputKg-dto.wasteKg;if(balance<-0.001)throw new BadRequestException('Entry exceeds issued yarn');await this.prisma.knittingJob.update({where:{id:jobId},data:{status:'RUNNING'}});return this.prisma.knittingProductionEntry.create({data:{knittingJobId:jobId,workerId:user.id,shift:dto.shift,outputKg:dto.outputKg,wasteKg:dto.wasteKg,balanceKg:balance,notes:dto.notes}});}
 async approveKnitting(entryId:string,dto:ApproveKnittingDto,user:AuthUser){return this.prisma.$transaction(async tx=>{const e=await tx.knittingProductionEntry.findUnique({where:{id:entryId},include:{knittingJob:true}});if(!e)throw new NotFoundException('Knitting entry not found');if(e.approved)throw new BadRequestException('Entry already approved');const rollNo=dto.rollNo||documentNo('GR');await tx.knittingProductionEntry.update({where:{id:entryId},data:{approved:true}});const roll=await tx.greyFabricRoll.create({data:{rollNo,knittingJobId:e.knittingJobId,fabricType:e.knittingJob.fabricType,gsm:e.knittingJob.gsm,diameter:e.knittingJob.diameter,weightKg:e.outputKg,warehouseCode:dto.greyWarehouseId,qcStatus:'PASSED'}});await this.inventory.createTxn({category:'GREY_FABRIC',txnType:'GREY_FABRIC_IN',itemCode:`GREY:${e.knittingJob.fabricType}`,itemName:`Grey ${e.knittingJob.fabricType}`,lotNo:rollNo,warehouseId:dto.greyWarehouseId,quantityIn:Number(e.outputKg),referenceType:'KNITTING_ENTRY',referenceId:e.id,productionOrderId:e.knittingJob.productionOrderId,createdById:user.id},tx);if(Number(e.wasteKg)>0)await tx.wasteEntry.create({data:{productionOrderId:e.knittingJob.productionOrderId,process:'Knitting',quantityKg:e.wasteKg,reason:'Knitting waste',workerName:e.workerId,approvedBy:user.id}});return {success:true,data:roll};});}
 async createDyeingBatch(dto:CreateDyeingBatchDto,user:AuthUser){if(!dto.rollIds.length)throw new BadRequestException('Select grey fabric rolls');return this.prisma.$transaction(async tx=>{const rolls=await tx.greyFabricRoll.findMany({where:{id:{in:dto.rollIds}},include:{knittingJob:true}});if(rolls.length!==dto.rollIds.length)throw new BadRequestException('One or more rolls not found');const total=rolls.reduce((a,r)=>a+Number(r.weightKg),0);if(total+0.001<dto.plannedQtyKg)throw new BadRequestException('Selected roll weight is below planned quantity');const batch=await tx.dyeingBatch.create({data:{batchNo:documentNo('DY'),productionOrderId:dto.productionOrderId,color:dto.color,shade:dto.shade,plannedQtyKg:dto.plannedQtyKg,machineId:dto.machineId,recipeId:dto.recipeId,assignedWorkerId:dto.assignedWorkerId,status:'MATERIAL_ISSUED',rolls:{create:rolls.map(r=>({greyRollId:r.id,inputKg:r.weightKg}))}}});for(const r of rolls){await this.inventory.requireStock('GREY_FABRIC',`GREY:${r.fabricType}`,dto.greyWarehouseId,Number(r.weightKg),r.rollNo,tx);await this.inventory.createTxn({category:'GREY_FABRIC',txnType:'DYEING_ISSUE',itemCode:`GREY:${r.fabricType}`,itemName:`Grey ${r.fabricType}`,lotNo:r.rollNo,warehouseId:dto.greyWarehouseId,quantityOut:Number(r.weightKg),referenceType:'DYEING_BATCH',referenceId:batch.id,productionOrderId:dto.productionOrderId,createdById:user.id},tx);}if(dto.assignedWorkerId)await tx.notification.create({data:{userId:dto.assignedWorkerId,title:'New dyeing batch assigned',message:`${batch.batchNo} • ${dto.color} • ${total.toFixed(2)} KG`,type:'JOB_ASSIGNED',referenceType:'DYEING_BATCH',referenceId:batch.id}});return batch;});}
 async dyeingEntry(batchId:string,dto:DyeingEntryDto,user:AuthUser){const b=await this.prisma.dyeingBatch.findUnique({where:{id:batchId}});if(!b)throw new NotFoundException('Dyeing batch not found');this.canWork(user,b.assignedWorkerId);const balance=dto.inputKg-dto.outputKg-dto.lossKg-dto.rejectedKg;if(balance<-0.001)throw new BadRequestException('Output + loss + reject cannot exceed input');await this.prisma.dyeingBatch.update({where:{id:batchId},data:{status:'RUNNING'}});return this.prisma.dyeingEntry.create({data:{batchId,workerId:user.id,processName:dto.processName,inputKg:dto.inputKg,outputKg:dto.outputKg,lossKg:dto.lossKg,rejectedKg:dto.rejectedKg,balanceKg:balance,temperature:dto.temperature,durationMin:dto.durationMin}});}
 async approveDyeing(entryId:string,user:AuthUser){return this.prisma.$transaction(async tx=>{const e=await tx.dyeingEntry.findUnique({where:{id:entryId},include:{batch:true}});if(!e)throw new NotFoundException('Dyeing entry not found');if(e.approved)throw new BadRequestException('Already approved');await tx.dyeingEntry.update({where:{id:entryId},data:{approved:true}});if(Number(e.lossKg)+Number(e.rejectedKg)>0)await tx.wasteEntry.create({data:{productionOrderId:e.batch.productionOrderId,process:'Dyeing',quantityKg:Number(e.lossKg)+Number(e.rejectedKg),reason:'Dyeing process loss/rejection',workerName:e.workerId,approvedBy:user.id}});return {success:true,message:'Dyeing entry approved'};});}
 createFinishing(dto:CreateFinishingDto){const balance=dto.inputKg-dto.outputKg-dto.lossKg;if(Math.abs(balance)>0.01)throw new BadRequestException(`Finishing is not balanced (${balance.toFixed(3)} KG)`);return this.prisma.finishingJob.create({data:{jobNo:documentNo('FN'),...dto,status:'COMPLETED'}});}
 async finalQc(dto:FinalQcDto,user:AuthUser){const balance=dto.inputKg-dto.approvedKg-dto.rejectedKg-dto.reworkKg;if(Math.abs(balance)>0.01)throw new BadRequestException(`QC quantity is not balanced (${balance.toFixed(3)} KG)`);return this.prisma.$transaction(async tx=>{const inspection=await tx.qualityInspection.create({data:{inspectionNo:documentNo('QC'),productionOrderId:dto.productionOrderId,stage:dto.stage,status:dto.approvedKg>0?'PASSED':dto.reworkKg>0?'REWORK':dto.rejectedKg>0?'REJECTED':'PENDING',inputKg:dto.inputKg,approvedKg:dto.approvedKg,rejectedKg:dto.rejectedKg,reworkKg:dto.reworkKg,inspectorId:user.id,measurements:dto.measurements as any,notes:dto.notes}});let roll=null;if(dto.approvedKg>0){const po=await tx.productionOrder.findUnique({where:{id:dto.productionOrderId},include:{salesOrderItem:true}});if(!po)throw new NotFoundException('Production order not found');const rollNo=dto.rollNo||documentNo('FR');roll=await tx.finishedFabricRoll.create({data:{rollNo,productionOrderId:dto.productionOrderId,color:po.salesOrderItem.color,gsm:po.salesOrderItem.gsm,width:po.salesOrderItem.width,netWeightKg:dto.approvedKg,qcStatus:'PASSED',warehouseCode:dto.warehouseId}});await this.inventory.createTxn({category:'FINISHED_FABRIC',txnType:'QC_APPROVED',itemCode:`FIN:${po.salesOrderItem.fabricType}:${po.salesOrderItem.color}`,itemName:`${po.salesOrderItem.fabricType} ${po.salesOrderItem.color}`,lotNo:rollNo,warehouseId:dto.warehouseId,quantityIn:dto.approvedKg,referenceType:'QUALITY_INSPECTION',referenceId:inspection.id,productionOrderId:dto.productionOrderId,createdById:user.id},tx);}if(dto.rejectedKg>0)await tx.wasteEntry.create({data:{productionOrderId:dto.productionOrderId,process:'Final QC',quantityKg:dto.rejectedKg,reason:'QC rejected',approvedBy:user.id}});return {inspection,roll};});}
 async approvals(){const [yarn,knitting,dyeing]=await Promise.all([this.prisma.yarnProductionEntry.findMany({where:{approved:false},include:{productionOrder:true},orderBy:{createdAt:'desc'}}),this.prisma.knittingProductionEntry.findMany({where:{approved:false},include:{knittingJob:true},orderBy:{createdAt:'desc'}}),this.prisma.dyeingEntry.findMany({where:{approved:false},include:{batch:true},orderBy:{createdAt:'desc'}})]);return {yarn,knitting,dyeing};}
}
