import { IsArray, IsNotEmpty, IsNumber, IsOptional, IsString, IsUUID, Min } from 'class-validator';
export class YarnEntryDto { @IsUUID() productionOrderId!:string; @IsString() @IsNotEmpty() processName!:string; @IsString() @IsNotEmpty() lotNo!:string; @IsString() @IsNotEmpty() yarnCount!:string; @IsOptional() @IsString() machineCode?:string; @IsOptional() @IsString() shift?:string; @IsNumber() @Min(0) inputKg!:number; @IsNumber() @Min(0) outputKg!:number; @IsNumber() @Min(0) wasteKg!:number; }
export class ApproveYarnDto { @IsString() warehouseId!:string; }
export class CreateKnittingJobDto { @IsString() productionOrderId!:string; @IsString() yarnLotNo!:string; @IsString() yarnCount!:string; @IsString() fabricType!:string; @IsOptional() @IsNumber() gsm?:number; @IsOptional() @IsString() diameter?:string; @IsOptional() @IsString() gauge?:string; @IsOptional() @IsString() machineId?:string; @IsOptional() @IsString() assignedWorkerId?:string; @IsString() yarnWarehouseId!:string; @IsNumber() @Min(0.001) yarnIssuedKg!:number; }
export class KnittingEntryDto { @IsNumber() @Min(0) outputKg!:number; @IsNumber() @Min(0) wasteKg!:number; @IsOptional() @IsString() shift?:string; @IsOptional() @IsString() notes?:string; }
export class ApproveKnittingDto { @IsString() greyWarehouseId!:string; @IsOptional() @IsString() rollNo?:string; }
export class CreateDyeingBatchDto { @IsString() productionOrderId!:string; @IsString() color!:string; @IsOptional() @IsString() shade?:string; @IsNumber() @Min(0.001) plannedQtyKg!:number; @IsOptional() @IsString() machineId?:string; @IsOptional() @IsString() recipeId?:string; @IsOptional() @IsString() assignedWorkerId?:string; @IsString() greyWarehouseId!:string; @IsArray() rollIds!:string[]; }
export class DyeingEntryDto { @IsString() processName!:string; @IsNumber() @Min(0) inputKg!:number; @IsNumber() @Min(0) outputKg!:number; @IsNumber() @Min(0) lossKg!:number; @IsNumber() @Min(0) rejectedKg!:number; @IsOptional() @IsNumber() temperature?:number; @IsOptional() @IsNumber() durationMin?:number; }
export class CreateFinishingDto { @IsString() productionOrderId!:string; @IsString() processName!:string; @IsNumber() inputKg!:number; @IsNumber() outputKg!:number; @IsNumber() lossKg!:number; @IsOptional() @IsNumber() gsmBefore?:number; @IsOptional() @IsNumber() gsmAfter?:number; @IsOptional() @IsString() widthBefore?:string; @IsOptional() @IsString() widthAfter?:string; }
export class FinalQcDto { @IsString() productionOrderId!:string; @IsString() stage!:string; @IsNumber() inputKg!:number; @IsNumber() approvedKg!:number; @IsNumber() rejectedKg!:number; @IsNumber() reworkKg!:number; @IsString() warehouseId!:string; @IsOptional() @IsString() rollNo?:string; @IsOptional() measurements?:Record<string,unknown>; @IsOptional() @IsString() notes?:string; }
